"use client";
import Head from 'next/head'
import { useRouter } from 'next/navigation'
import styles from '@/styles/Home.module.css'
import { useContext, useEffect, useMemo } from 'react';
import { SpotifyAccessTokenContext } from '@/pages/_app';
import axios from 'axios';
import { read } from 'fs';

export default function Home() {
  const router = useRouter();

  const clientId = process.env.NEXT_PUBLIC_CLIENT_ID
  const redirectUri = process.env.NEXT_PUBLIC_REDIRECT_URI
  const encodedRedirectUri = useMemo(() => encodeURIComponent(redirectUri || ""), [redirectUri]);
  const scopes = ['user-library-read', 'user-library-modify', 'user-top-read', 'user-read-recently-played'].join('%20');

  const {
    accessToken,
    refreshToken,
  } = useContext(SpotifyAccessTokenContext);

  useEffect(() => {
    if (!clientId || !redirectUri) return;

    if (!accessToken || !refreshToken) {
      router.push(`https://accounts.spotify.com/authorize?response_type=code&client_id=${clientId}&redirect_uri=${encodedRedirectUri}&scope=${scopes}`);
      return;
    }

    // if (accessToken) {
    //   const getTrack = async () => {
    //     const response = await axios({
    //       method: 'get',
    //       url: 'https://api.spotify.com/v1/me/top/tracks',
    //       headers: {
    //         'Content-Type': 'application/json',
    //         Authorization: `Bearer ${accessToken}`,
    //       }
    //     })

    //     console.log("test", response)
    //   }
    //   getTrack();
    // }
  }, [router, clientId, redirectUri, scopes, encodedRedirectUri, accessToken, refreshToken])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Spotify test link
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
